baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Rusti-Blog"
theme = 'PaperMod'

[params]
ShowReadingTime = true
ShowPostNavLinks = true
socialIcons = [
    {name = "twitter", url = "https://twitter.com/"},
    {name = "stackoverflow", url = "https://stackoverflow.com"},
    {name = "github", url = "https://github.com/" }
]
